name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.mryashdoc }}
        password: ${{ secrets.dckr_pat_YOtdb4_7xgFL6Y3HTKWQpMTL710 }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: YOUR_DOCKERHUB_USERNAME/my-app-code:latest
